default_language_version:
  python: python3.10
fail_fast: true
exclude: '^.idea'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: f71fa2c1f9cf5cb705f73dffe4b21f7c61470ba9  # frozen: v4.4.0
    hooks:
    - id: fix-byte-order-marker
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-merge-conflict
    - id: check-json
    - id: check-toml
    - id: check-yaml
    - id: check-vcs-permalinks
    - id: debug-statements
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: trailing-whitespace
  - repo: https://github.com/ambv/black
    rev: 2ddea293a88919650266472186620a98a4a8bb37  # frozen: 22.12.0
    hooks:
    - id: black
      language_version: python3.10
  - repo: https://github.com/AleksaC/hadolint-py
    rev: ecf2d2c004e7a753f48e44952a81d7c9cf1f202c  # frozen: v2.10.0
    hooks:
      - id: hadolint
