default_language_version:
  python: python3.9
fail_fast: true
exclude: '^.idea'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 38b88246ccc552bffaaf54259d064beeee434539  # frozen: v4.0.1
    hooks:
    - id: fix-byte-order-marker
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-merge-conflict
    - id: check-json
    - id: check-toml
    - id: check-yaml
    - id: check-vcs-permalinks
    - id: debug-statements
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: trailing-whitespace
  - repo: https://github.com/ambv/black
    rev: 64c8be01f0cfedc94cb1c9ebd342ea77cafbb78a  # frozen: 21.10b0
    hooks:
    - id: black
      language_version: python3.9
