default_language_version:
  python: python3.10
fail_fast: true
exclude: '^.idea'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 8fe62d14e0b4d7d845a7022c5c2c3ae41bdd3f26  # frozen: v4.1.0
    hooks:
    - id: fix-byte-order-marker
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-merge-conflict
    - id: check-json
    - id: check-toml
    - id: check-yaml
    - id: check-vcs-permalinks
    - id: debug-statements
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: trailing-whitespace
  - repo: https://github.com/ambv/black
    rev: fc0be6eb1e2a96091e6f64009ee5e9081bf8b6c6  # frozen: 22.1.0
    hooks:
    - id: black
      language_version: python3.10
  - repo: https://github.com/AleksaC/hadolint-py
    rev: 10ecfcc7abe63a83216eba9cbb01cca36ae54622  # frozen: v2.8.0
    hooks:
      - id: hadolint
