#!/usr/bin/env sh

GIT_HASH=$(git rev-parse --short HEAD)
BUILD_DATE=$(date --rfc-3339=seconds)
VERSION=$( (git describe --tags || echo "dev") | sed -nr "s/v(.*)/\1/p")

sed -i "1iARG GIT_HASH=\"${GIT_HASH}\"" Dockerfile
sed -i "1iARG VERSION=\"${VERSION}\"" Dockerfile
sed -i "1iARG BUILD_DATE=\"${BUILD_DATE}\"" Dockerfile
echo "VERSION = \"${VERSION}\"" > kibana_prometheus_exporter/_version.py
